mlb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('',include('thread.urls')),
    path('', include('account.urls')),
    
]

thread/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from .views import (CommentViewSet, GameThreadListView, dislike_view,
                    gamethread_details, like_view, home, user_logout)

router = routers.DefaultRouter()
router.register('comments', CommentViewSet)

app_name = 'thread_app'

urlpatterns = [
    path('', home, name='home'),
    path('',include(router.urls)),
    path('game-threads/', GameThreadListView.as_view(), name='gamethread_list'),
    path('<int:pk>/', gamethread_details, name='gamethread_detail'),
    path('like/<int:pk>/<int:id>', like_view, name='like_comment'),
    path('dislike/<int:pk>/<int:id>', dislike_view, name='dislike_comment'),
    path('logged_out/',user_logout, name='user_logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{% static 'css/addons/datatables-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables-select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/addons/datatables2.min.css' %}" rel="stylesheet">
    {% block extrahead%}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrashStars</title>
</head>
<body class="black-skin">
{% block styles %}
    {% endblock %}
<style>
table.dataTable thead .sorting:after,
table.dataTable thead .sorting:before,
table.dataTable thead .sorting_asc:after,
table.dataTable thead .sorting_asc:before,
table.dataTable thead .sorting_asc_disabled:after,
table.dataTable thead .sorting_asc_disabled:before,
table.dataTable thead .sorting_desc:after,
table.dataTable thead .sorting_desc:before,
table.dataTable thead .sorting_desc_disabled:after,
table.dataTable thead .sorting_desc_disabled:before {
bottom: .5em;
}
    html,
    body,
    header,
    .jarallax {
      height: 100%;
    }
</style>


<!-- Navigation & Intro -->

<section >
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar ">
        <div class="container">
            <a class="navbar-brand" href="{% url 'thread_app:home' %}">TrashStars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'thread_app:home' %}">Home <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'thread_app:gamethread_list' %}" >Game Thread</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'thread_app:user_logout' %}">
                            Logout
                        </a>
                    </li>
                    {% else %}
                    {% endif %}
                    
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" href="#timetable" data-offset="100">Timetable</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#tickets" data-offset="100">Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact" data-offset="100">Contact</a>
                    </li>  {% endcomment %}
                </ul>

                <!-- Social Icon  -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a class="nav-link" href=""><i class="fab fa-facebook-f light-green-text-2"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"><i class="fab fa-twitter light-green-text-2"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"><i class="fab fa-instagram light-green-text-2"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</section>
<!-- Navigation & Intro -->

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- JQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- MDBootstrap Datatables  -->
    <script type="text/javascript" src="{% static 'js/addons/datatables2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables-select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/addons/datatables-select.min.js' %}"></script>
    {% comment %} <script type="text/javascript" src="{% static 'js/token.js' %}"></script> {% endcomment %}
    <script>
        $(document).ready(function () {
            new WOW().init();
            $('[data-toggle="tooltip"]').tooltip()
            $('[data-toggle="popover-hover"]').popover()
        });
    </script>

    {% block scripts %}
    {% endblock %}
</body>
</html>