account/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register

app_name = 'account_app'
urlpatterns = [
    path('register/',register, name='register'),
]

mlb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('',include('thread.urls')),
    path('', include('account.urls')),
    
]

thread/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from .views import (CommentViewSet, GameThreadListView, dislike_view,
                    gamethread_details, like_view, home, user_logout)

router = routers.DefaultRouter()
router.register('comments', CommentViewSet)

app_name = 'thread_app'

urlpatterns = [
    path('', home, name='home'),
    path('',include(router.urls)),
    path('game-threads/', GameThreadListView.as_view(), name='gamethread_list'),
    path('<int:pk>/', gamethread_details, name='gamethread_detail'),
    path('like/<int:pk>/<int:id>', like_view, name='like_comment'),
    path('dislike/<int:pk>/<int:id>', dislike_view, name='dislike_comment'),
    path('logged_out/',user_logout, name='user_logout'),
]

thread/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import length, slugify
from django.urls import reverse


# Create your models here.
class GameThread(models.Model):
    date = models.DateField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return str(self.date)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.date)
        super(GameThread, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-date']

class Comment(models.Model):
    by = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_body = models.TextField(max_length=300, blank=True)
    thread = models.ForeignKey(GameThread, on_delete=models.CASCADE, related_name='thread_comments')
    date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return '(' + str(self.by.profile.team) + ')' + str(self.by) + ' - ' + self.comment_body

thread/forms.py
from django import forms
from django.forms.models import ModelForm
from .models import Comment
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_body',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['comment_body'].label = 'Give it your best shot.....'

thread/views.py
import datetime
from requests.api import get

import statsapi
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, ListView, TemplateView
from rest_framework import viewsets
from django.http import request, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

from thread.models import Comment, GameThread
from django.contrib.auth.decorators import login_required

from .forms import CommentForm
from .models import *
from .serializers import CommentSerializer


# Create your views here.
def home(request):
    year = datetime.datetime.now().year
    month = datetime.datetime.now().month
    day = datetime.datetime.now().day
    today = datetime.datetime.now()
    yesterday = datetime.datetime.now().day - 1
    last_game = statsapi.schedule(date=str(year) + "-" + str(month) +"-" + str(yesterday), team=135)
    next_game = statsapi.schedule(date=str(year) + "-" + str(month) +"-" + str(day), team=135)
    game_thread = GameThread.objects.all()
    # user = User.objects.get(id=request.user.id)
    # total_likes = user.likes.all().count()
        


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('thread_app:home'))

            else: 
                return HttpResponse('Account is not active!')
        
        else:
            print('someone tried to login unsuccessfully!')
            return HttpResponse('<h1 class="text-center">Username or Password does not match our records. Please try again.</h1>')

    else:
        context = {
        'last_game':last_game,
        'next_game':next_game,
        'game_thread':game_thread,
        
    }
        return render(request, 'thread/home.html', context=context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('thread_app:home'))

def like_view(request, id, pk):
    this_comment = get_object_or_404(Comment, pk=request.POST.get('comment_id'))
    if this_comment.dislikes.filter(id=request.user.id).exists():
        this_comment.dislikes.remove(request.user)
        this_comment.likes.add(request.user)
    else:
        this_comment.likes.add(request.user)
    return HttpResponseRedirect(reverse('thread_app:gamethread_detail', args=[str(id)]))

def dislike_view(request, id, pk):
    this_comment = get_object_or_404(Comment, pk=request.POST.get('comment_id1'))
    if this_comment.likes.filter(id=request.user.id).exists():
        this_comment.likes.remove(request.user)
        this_comment.dislikes.add(request.user)
    else:
        this_comment.dislikes.add(request.user)
    return HttpResponseRedirect(reverse('thread_app:gamethread_detail', args=[str(id)]))


def gamethread_details(request, pk):
    this_thread = GameThread.objects.get(pk=pk)  
    comments = Comment.objects.filter(thread=this_thread)
    comment_count = Comment.objects.filter(thread=this_thread).count()
    this_game = statsapi.schedule(date=this_thread, team=135)
    most_likes = comments.order_by('likes').last()
        
    
    if request.method == 'POST':
        form = CommentForm(data=request.POST)

        if form.is_valid():
            if 'comment_body' in request.POST:
                comment_form = form.save(commit=False)
                comment_form.by = request.user
                comment_form.thread = this_thread

                comment_form.save()
                form = CommentForm()
            return HttpResponseRedirect(reverse('thread_app:gamethread_detail', args=[str(pk)]))

        else:
            print(form.errors)
        
    else:
        form = CommentForm()
       

    context = {
        'this_game':this_game,
        'comments':comments,
        'comment_count':comment_count,
        'comment_form':form,
        'this_thread':this_thread,
        'most_likes':most_likes,
        
    }
    return render(request,'thread/gamethread_detail.html', context=context)

class GameThreadListView(ListView):
    model = GameThread
    context_object_name = 'gamethreads'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = datetime.datetime.now().year
        month = datetime.datetime.now().month
        day = datetime.datetime.now().day
        today = datetime.datetime.now()
        
        

        game_thread, created = GameThread.objects.get_or_create(date=today)
        game_thread.value = self.request.POST.get(today)
        game_thread.save()
        # game_threads = GameThread.objects.exclude(date=today)
        # game_threads.delete()
        
        context['game'] = statsapi.schedule(date=str(year) + "-" + str(month) +"-" + str(day), team=135)
        
        return context
    
class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

thread/templates/thread/gamethread_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content%}
<div class="card text-center mt-3">
    <div class="card-body ">
        <h2 class="card-title">
        {% for x in this_game %}
            {% if x.winning_team == 'San Diego Padres' %}
                Padres Win Bitch!
            {% endif %}
                {{x.summary}}
        {% endfor %}
        </h2>
    </div>
</div>

<h3 class='mt-3 text-center'> <i class="red-text fas fa-fire-alt "></i> Best comment <i class="red-text fas fa-fire-alt "></i>
<div class="alert alert-warning text-center" role="alert">
  {{ most_likes }}
</div>
<!-- Section: Comments list -->
<section class="mb-5 mt-5 wow fadeIn" data-wow-delay="0.3s">
    <!-- Main wrapper -->
    <div class="comments-list text-center text-md-left">
        {% for c in comments %}
        <!-- First row -->
        <div class="row ">
            <!-- Image column -->
            {% comment %} <div class="col-sm-2 col-12 mb-md-0">
                <img src="{% static 'img/SDlogo.jpg' %}" class="avatar rounded-circle z-depth-1-half">
            </div> {% endcomment %}
            <!-- Content column -->
            <div class="col-sm-10 col-12">
                <a>
                    <h4 class="font-weight-bold">
                        {% if c.likes.count > c.dislikes.count %}
                           ({{ user.profile.team }})  @{{ c.by }} is <i class="red-text fas fa-fire-alt "></i>
                        {% elif c.dislikes.count > c.likes.count %}
                           ({{ user.profile.team }})  @{{ c.by }} is <i class="fas fa-dumpster "></i>
                        {% else %}
                           ({{ user.profile.team }}) @{{ c.by }}
                        {% endif %}
                    </h4>
                </a>
                    <div class="mt-2">
                        <ul class="list-unstyled">
                            <li class="comment-date">
                            <small><i class="far fa-calendar-alt"></i> {{ c.date|date:'m/d/y' }}</small></li>
                        </ul>
                    </div>
                    {% if c.dislikes.count > c.likes.count %}
                    <div class="view">
                        <p class="grey-text">{{ c.comment_body }}</p>
                        <div class="mask rgba-white-strong">
                        </div>
                    </div>
                    {% else %}
                        <p class="grey-text">{{ c.comment_body }}</p>
                    {% endif %}
                {% if user.is_authenticated %}
                <div class='row'>
                    <div class='col-auto'>
                        <form method='POST' action="{% url 'thread_app:like_comment' c.id this_thread.id %}">
                        {% csrf_token %}
                            <button data-toggle='tooltip' data-placement="top" title="This comment is fire!" name='comment_id' id='comment_id' value='{{c.id}}' type='submit' class='btn btn-link btn-lg'><span class="badge badge-pill brown darken-4">{{ c.likes.count }} <i class="fas fa-fire-alt"></i></span></button>
                            
                        </form>
                    </div>
                    <div class='col-auto'>
                        <form method='POST' action="{% url 'thread_app:dislike_comment' c.id this_thread.id %}">
                        {% csrf_token %}
                            <button data-toggle='tooltip' data-placement="top" title="This comment is trash!" name='comment_id1' id='comment_id1' value='{{c.id}}' type='submit' class='btn btn-link btn-lg'><span class="badge badge-pill brown darken-4">{{ c.dislikes.count }} <i class="fas fa-dumpster"></i></span></button>
                            
                        </form>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Content column -->
        </div>
        <!-- First row -->
        <hr>
    
        {% endfor %}
    </div>
    <!-- Main wrapper -->
</section>
<!-- Section: Comments list -->

<!--Comment Form-->
<section>
    <div class="card">
        <div class="card-body pt-3 px-lg-5 pt-0">
        {% if user.is_authenticated %}
            <form method='POST'>
            {% csrf_token %}
            {% bootstrap_form comment_form %}
                <input  class="btn btn-outline-dark btn-rounded btn-block z-depth-0 my-4 waves-effect" value="Send It!" type="submit">
            </form>
        {% else %}
        <h2>Please login to comment!</h2>
        {% endif %}
        </div>
    </div>
</section>
<!--Comment Form--> 

{% block scripts %}
{% endblock %}
{% endblock%}

thread/templates/thread/gamethread_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container-fluid mt-5">
    <!--Section: Content-->
    <section>
    <style>
    .news-tile .card-title {
    position: absolute;
    bottom: 15px;
    left: 40px;
    }

    .rgba-stylish-strong {
    background-color: rgba(62, 69, 81, .5);
    }
    </style>
        <!--Grid row-->
        <div class="row">
        {% for g in gamethreads %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-12 mb-4">
                <!--News tile -->
                <div class="news-tile view zoom z-depth-1 rounded mb-4">
                    <h3><span class="ml-2 mt-2 badge  brown darken-4">{{ g.thread_comments.count }} <i class="far fa-comments" aria-hidden="true"></i></span></h3>
                    <a href="{% url 'thread_app:gamethread_detail' g.pk %}" class="text-white">
                        <img src="{% static 'img/friarLogo.png'%}" class="img-fluid rounded-bottom" alt="friar logo">
                        <div class="mask rgba-stylish-strong">
                            <div class="text-white text-center py-lg-5 py-0 my-0">
                                <div>
                                    <h3 class="card-title text-center font-weight-bold pt-2">
                                        <span class='badge brown darken-4'>
                                            <strong>Game thread for {{ g.date|date:'m/d/y' }}</strong>
                                        </span>
                                    </h3>
                                    <p class="mx-5 clearfix d-none d-md-block">
                                        <span class='badge'>
                                        {% for g in games %}
                                            {% if not g.winning_team %}
                                                {{ g.summary }}
                                            {% else %}
                                                The {{ g.winning_team }} beat the {{ g.losing_team }}
                                            {% endif %}
                                        {% endfor %}
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <!--News tile -->
            </div>
            <!--Grid column-->
        {% endfor %}
        </div>
    <!--Grid row-->
    </section>
<!--Section: Content-->
</div>
{% endblock %}

thread/templates/thread/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='row mt-3'>
    <div class='col'>
        <h3 class='ml-md-5 font-weight-bold animated fadeInLeftBig slower delay-.3s'>
            {% for g in last_game %}
                {% if not g %}
                    No Game 
                {% else %}
                    {{g.summary}} 
                {% endif %}
            {% endfor %}
        </h3>
    </div>
    <div class='col'>
        <h3 class='ml-md-5 font-weight-bold animated fadeInLeftBig slower'>
            {% for n in next_game %}
                {% if not n %}
                    No Game 
                {% else %}
                    {{ n.summary }}
                {% endif %}
            {% endfor %}
        </h3>
    </div>
</div>
<div class="container-fluid mt-3 mb-5" id='info'>
    <!-- Full Page Intro -->
    <section>
        <!-- Mask & flexbox options-->
        <div class="mask d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="container py-5 my-5">
                <!--Grid row-->
                <div class="row d-flex align-items-center justify-content-center">
                    <!--Grid column-->
                    <div class="col-md-6 col-xl-6">
                    {% if user.is_authenticated %}
                        <h1 class='text-brown'>Welcome Back {{ user }}</h1>
                    {% else %}
                        <div class="container my-5 py-5 z-depth-1">
                            <!--Section: Content-->
                            <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
                                <!--Grid row-->
                                <div class="row d-flex justify-content-center">
                                    <!--Grid column-->
                                    <div class="col-md-12">
                                        <!-- Default form login -->
                                        <form class="text-center" method='POST'>
                                            {% csrf_token %}
                                            <p class="h4 mb-4">Sign in</p>
                                            <!-- Email -->
                                            <input type="text" name='username' class="form-control mb-4" placeholder="@username">
                                            <!-- Password -->
                                            <input type="password" name="password" class="form-control mb-4" placeholder="Password">
                                            <!-- Sign in button -->
                                            <input class="btn btn-outline-dark btn-block my-4" type="submit" value='Sign in'>

                                            <!-- Register -->
                                            <p>Not a member?
                                                <a href="{% url 'account_app:register' %}">Register</a>
                                            </p>
                                        </form>
                                        <!-- Default form login -->
                                    </div>
                                    <!--Grid column-->
                                </div>
                                <!--Grid row-->
                            </section>
                            <!--Section: Content-->
                        </div>
                    {% endif %}
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </div>
            <!-- Content -->
        </div>
<!-- Mask & flexbox options-->
    </section>
<!-- Full Page Intro -->
</div>
{% if user.is_authenticated%}
{{ total_likes }}
{% endif %}

{% endblock %}